/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this OnEnter
void main()
{

object oPC = GetEnteringObject();

if (!GetIsPC(oPC)) return;

object oTarget;
oTarget = GetObjectByTag("DOOR_BONE4");

SetLocked(oTarget, TRUE);

AssignCommand(oTarget, ActionCloseDoor(oTarget));

oTarget = GetObjectByTag("DOOR_BONE5");

SetLocked(oTarget, TRUE);

AssignCommand(oTarget, ActionCloseDoor(oTarget));

}

