/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this OnUsed
void main()
{

object oPC = GetLastUsedBy();

if (!GetIsPC(oPC)) return;

object oTarget;
oTarget = GetObjectByTag("DOOR_BONE2");

SetLocked(oTarget, FALSE);

SendMessageToPC(oPC, "You hear the sound of a door being unlocked somewhere within the chamber...");

}
