/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this OnEnter
void main()
{

object oPC = GetEnteringObject();

if (!GetIsPC(oPC)) return;

AssignCommand(GetObjectByTag("BBS_SCRIBE2"), ActionSpeakString("Talk to me if you want to use the bulletin board!"));

}

